# Generated by Django 4.2.5 on 2024-01-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instiute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instute_name", models.CharField(max_length=40, unique=True)),
                (
                    "instute_type",
                    models.CharField(
                        choices=[("S", "School"), ("CL", "College"), ("H", "Hostel")],
                        max_length=30,
                    ),
                ),
                ("courses_provided", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("father_name", models.CharField(max_length=100)),
                ("student_id", models.CharField(max_length=20, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("parent_number", models.CharField(max_length=15)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("fees_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fees_unpaid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("address", models.TextField()),
            ],
        ),
    ]
