# Generated by Django 4.2.5 on 2024-01-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="institute",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.instiute",
            ),
        ),
        migrations.AlterField(
            model_name="instiute",
            name="courses_provided",
            field=models.JSONField(
                blank=True,
                choices=[("Bcom", "Bcom"), ("BBA", "BBA"), ("BCA", "BCA")],
                default=list,
            ),
        ),
    ]
