# Generated by Django 4.2.5 on 2024-01-20 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_student_student_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instiute",
            old_name="instute_name",
            new_name="instiute_name",
        ),
        migrations.RenameField(
            model_name="instiute",
            old_name="instute_type",
            new_name="instiute_type",
        ),
    ]
