# Generated by Django 4.2.5 on 2024-01-20 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_rename_instute_name_instiute_instiute_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instiute",
            old_name="instiute_name",
            new_name="institute_name",
        ),
        migrations.RenameField(
            model_name="instiute",
            old_name="instiute_type",
            new_name="institute_type",
        ),
    ]
