# Generated by Django 4.2.5 on 2024-01-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_remove_instiute_courses_provided"),
    ]

    operations = [
        migrations.AddField(
            model_name="instiute",
            name="courses_provided",
            field=models.JSONField(
                blank=True,
                choices=[("Bcom", "Bcom"), ("BBA", "BBA"), ("BCA", "BCA")],
                default=list,
            ),
        ),
    ]
