# Generated by Django 4.2.5 on 2024-01-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_instiute_courses_provided"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="pincode",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="state",
            field=models.CharField(default="", max_length=50),
        ),
    ]
