# Generated by Django 4.2.5 on 2024-01-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_student_city_student_pincode_student_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="division",
            field=models.CharField(default="A", max_length=5),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
